### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ANU4247**
@Jay-study-nildana Sir,
i tried creating a seo friendly meta data ,
and some changes in title 
hope u will like it.
Open for suggestions

### CODE REVIEW

**Comment by ANU4247** [comment]
waiting for repose and suggestion

**Comment by Jay-study-nildana** [comment]
@ANU4247 

ah, you have opened a pull request. good, I will check it out. hold on.

**Review by Jay-study-nildana — APPROVED** [review]

**Comment by Jay-study-nildana** [comment]
@ANU4247 

congratulations. You are officially the first contributor to my open source project. 

I thank you very much.

Jay.

**Comment by Jay-study-nildana** [comment]
@ANU4247 

As promised, I have sent you an invite to our exclusive team only for developers on github.

Thanks and looking forward to more contributions.

Jay.

**Pull request merged**
