### PR TITLE
added contributors list style

### PR DESCRIPTION
**Pull request by ANU4247**

### CODE REVIEW

**Comment by Jay-study-nildana** [comment]
@ANU4247 

what does this pull request do. I don't know this code :) 

could you add a description when you create commits and pull requests?

Thanks

Jay

**Comment by Jay-study-nildana** [comment]
@ANU4247 

Oh, okay, now I understand. this is connected to other pull request. 

https://github.com/BigbabeeSmallbabee/ProjectBFSDFHQFrontEndVanillaJS/pull/5

Okay, okay. still, please add description for future pull requests my friend. 

Thanks

Jay

**Comment by Jay-study-nildana** [comment]
Also, you are not tagging me when you create pull request. 

If there is no tagging, I don't get notified. I only saw this pull request by accident. So, remember to tag when you create pull request. 

And of course, message me on discord, if I don't reply to anything you do within 1 or 2 days. 

Thanks

Jay

**Comment by ANU4247** [comment]
> Also, you are not tagging me when you create pull request. 
> 
> If there is no tagging, I don't get notified. I only saw this pull request by accident. So, remember to tag when you create pull request. 
> 
> And of course, message me on discord, if I don't reply to anything you do within 1 or 2 days. 
> 
> Thanks
> 
> Jay

Sir that css one 
This css merge request does that it removes all free space which is waste and helps us to make our site responsive in easy and efficient manner..

**Pull request merged**
